---
- name: Check existing install
  register: logstash_exporter_version_check
  failed_when: False
  changed_when: False
  check_mode: False
  ansible.builtin.shell: /usr/bin/logstash-exporter --version 2>&1
  tags:
    - logstash
    - logstash-exporter

- name: Fact version change
  ansible.builtin.set_fact:
    logstash_exporter_version_changed: "{{ logstash_exporter_version_check.rc != 0 or (logstash_exporter_version_check.stdout_lines is defined and logstash_exporter_version not in logstash_exporter_version_check.stdout_lines[0]) | bool }}"
  tags:
    - logstash
    - logstash-exporter

- name: Download exporter binary
  when: logstash_exporter_version_changed
  ansible.builtin.get_url:
    url: "{{ logstash_exporter_download }}"
    dest: /usr/bin/logstash-exporter
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - logstash
    - logstash-exporter

- name: Write default config
  notify:
    - Restart logstash-exporter
  ansible.builtin.template:
    src: exporter/default.j2
    dest: /etc/default/logstash-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - logstash
    - logstash-exporter

- name: Write service file
  notify:
    - Restart logstash-exporter
  ansible.builtin.template:
    src: exporter/service.j2
    dest: /etc/systemd/system/logstash-exporter.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - logstash
    - logstash-exporter

- name: Start logstash-exporter service
  ansible.builtin.systemd:
    name: logstash-exporter
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - logstash
    - logstash-exporter

...
