---
- name: Remove legacy repo
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ logstash_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: false
    state: absent
  tags:
    - logstash

- name: Remove legacy key
  ansible.builtin.apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: absent
  tags:
    - logstash

- name: Download repo key
  register: logstash_key_download
  ansible.builtin.get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: "{{ logstash_keyring }}.asc"
    mode: u=rw,g=r,o=r
    force: true
  tags:
    - logstash

- name: Check repo key
  register: logstash_key_status
  ansible.builtin.stat:
    path: "{{ logstash_keyring }}"
  tags:
    - logstash

- name: Dearmor repo key
  when:
    - logstash_key_download.changed or not logstash_key_status.stat.exists
  register: logstash_key_convert
  changed_when: logstash_key_convert.rc == 0
  ansible.builtin.command:
    cmd: "gpg --batch --yes --dearmor -o {{ logstash_keyring }} {{ logstash_keyring }}.asc"
  tags:
    - logstash

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ logstash_keyring }}] https://artifacts.elastic.co/packages/{{ logstash_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: true
    state: present
  tags:
    - logstash

- name: Create required group
  ansible.builtin.group:
    name: "{{ logstash_group }}"
    system: true
    state: present
  tags:
    - logstash

- name: Create required user
  ansible.builtin.user:
    name: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    password: "!"
    shell: /usr/sbin/nologin
    home: /usr/share/logstash
    create_home: false
    system: true
    state: present
  tags:
    - logstash

- name: Pin package version
  ansible.builtin.copy:
    content: |
      Explantion: Pin added by logstash role
      Package: logstash
      Pin: version 1:{{ logstash_server_version }}*
      Pin-Priority: 1000
    dest: /etc/apt/preferences.d/logstash
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - logstash

- name: Enforce man dir
  ansible.builtin.file:
    path: /usr/share/man/man1
    recurse: true
    owner: root
    group: root
  tags:
    - logstash

- name: Install required packages
  loop:
    - ca-certificates-java
    - "openjdk-{{ logstash_openjdk_version }}-jre"
    - "logstash=1:{{ logstash_server_version }}*"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  environment:
    JAVA_HOME: "{{ logstash_java_home }}"
  tags:
    - logstash

- name: Drop unused files
  loop:
    - /etc/logstash/logstash-sample.conf
    - /etc/logstash/startup.options
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  tags:
    - logstash

- name: Write log4j2 config
  notify:
    - Restart logstash
  ansible.builtin.copy:
    src: log4j2.properties
    dest: /etc/logstash/log4j2.properties
    owner: root
    group: "{{ logstash_group }}"
    mode: u=rw,g=rw,o=
  tags:
    - logstash

- name: Write logstash config
  notify:
    - Restart logstash
  ansible.builtin.template:
    src: config.j2
    dest: /etc/logstash/logstash.yml
    owner: root
    group: "{{ logstash_group }}"
    mode: u=rw,g=rw,o=
  tags:
    - logstash

- name: Write pipelines config
  notify:
    - Restart logstash
  ansible.builtin.template:
    src: pipelines.j2
    dest: /etc/logstash/pipelines.yml
    owner: root
    group: "{{ logstash_group }}"
    mode: u=rw,g=rw,o=
  tags:
    - logstash

- name: Write jvm config
  notify:
    - Restart logstash
  ansible.builtin.template:
    src: jvm.j2
    dest: /etc/logstash/jvm.options
    owner: root
    group: "{{ logstash_group }}"
    mode: u=rw,g=rw,o=
  tags:
    - logstash

- name: Write default config
  notify:
    - Restart logstash
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/logstash
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - logstash

- name: Start logstash service
  ansible.builtin.systemd:
    name: logstash
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - logstash

- name: Check installed plugins
  register: logstash_plugins_list
  changed_when: false
  ansible.builtin.command: /usr/share/logstash/bin/logstash-plugin list
  environment:
    JAVA_HOME: "{{ logstash_java_home }}"
  tags:
    - logstash

- name: Install defined plugins
  loop: "{{ logstash_install_plugins }}"
  when:
    - logstash_plugins_list.stdout is defined
    - (item if item.name is not defined else item.name) not in logstash_plugins_list.stdout
    - item.state is not defined or item.state == 'present'
  notify:
    - Restart logstash
  register: logstash_plugin_install
  changed_when: "'Installation successful' in logstash_plugin_install.stdout"
  failed_when: logstash_plugin_install.rc > 0
  ansible.builtin.command: "/usr/share/logstash/bin/logstash-plugin install {{ item if item.name is not defined else item.name }}"
  environment:
    JAVA_HOME: "{{ logstash_java_home }}"
  tags:
    - logstash

- name: Remove defined plugins
  loop: "{{ logstash_install_plugins }}"
  when:
    - logstash_plugins_list.stdout is defined
    - (item if item.name is not defined else item.name) in logstash_plugins_list.stdout
    - item.state is defined
    - item.state == 'absent'
  notify:
    - Restart logstash
  register: logstash_plugin_remove
  changed_when: "'Successfully removed' in logstash_plugin_remove.stdout"
  failed_when: logstash_plugin_remove.rc > 0
  ansible.builtin.command: "/usr/share/logstash/bin/logstash-plugin uninstall {{ item if item.name is not defined else item.name }}"
  environment:
    JAVA_HOME: "{{ logstash_java_home }}"
  tags:
    - logstash

- name: Include exporter tasks
  when:
    - logstash_exporter_enabled
  ansible.builtin.include_tasks: exporter.yml
  tags:
    - logstash
    - logstash-exporter

...
